# Configuracion por defecto del proyecto.
spring.application.name=Backend

# ------------------H2 DataBase.------------------

# "jdbc:h2:mem" hace referencia a la Memoria que se borra al apagar el servidor.
# "testdb" es el nombre de la base de datos.
spring.datasource.url=jdbc:h2:mem:testdb 

# Clase Java que habla con H2, por algo es "Driver..."
spring.datasource.driverClassName=org.h2.Driver

# Se le añade un usuaio Administrador por defecto.
spring.datasource.username=sa
# Con su respectiva contraseña.
spring.datasource.password=password

# ------------H2 Consoloe------------.

# Activa http://localhost:8080/h2-console

# Sirve para Inspeccionar datos visualmente.
# H2 Console habilitado
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --------------JPA / Hibernate---------.

# "dialect..." Indica que se use el idioma de H2(Sintaxys correcta).
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Borra y crea tablas / "Update" = Crea si no existe y mantiene datos.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola todas las consultas SQL.
spring.jpa.show-sql=true

# --------------JWT------------------
jwt.secret=tuClaveSecretaMuyLargaYSegura1234567890
jwt.expiration=86400
